steps:
  - name: "gcr.io/cloud-builders/wget"
    id: "Download and run Flyway"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        echo "=== Download Flyway ==="
        curl -L https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/10.12.0/flyway-commandline-10.12.0-linux-x64.tar.gz -o flyway.tar.gz
        tar -xvf flyway.tar.gz
        export PATH="/workspace/flyway-10.12.0:/usr/local/bin:/opt/flyway"

        echo "=== Download Cloud SQL Proxy ==="
        curl -o cloud-sql-proxy https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v2.11.0/cloud-sql-proxy.linux.amd64
        chmod +x cloud-sql-proxy

        echo "=== Start Cloud SQL Proxy in BACKGROUND ==="
        ./cloud-sql-proxy moonlit-academy-478519-t8:us-central1:books-db --port=3306 &

        echo "Waiting for proxy to start..."
        for i in {1..30}; do
          nc -z 127.0.0.1 3306 && echo "Proxy is ready!" && break
          echo "Proxy not ready yet... retrying"
          sleep 2
        done

        echo "=== Run Flyway Migration ==="
        ./flyway-10.12.0/flyway \
          -url=jdbc:mysql://127.0.0.1:3306/$_DB_NAME \
          -user=$_DB_USER \
          -password=$_DB_PASSWORD \
          -locations=filesystem:/workspace/Book_app/flyway/sql \
          -baselineOnMigrate=true \
          migrate

  - name: gcr.io/cloud-builders/docker
    args:
      [
        "build",
        "-t", "us-central1-docker.pkg.dev/moonlit-academy-478519-t8/book-app-docker-repo/book-app-image:$SHORT_SHA",
        "."
      ]

  - name: gcr.io/cloud-builders/docker
    args: ["push", "us-central1-docker.pkg.dev/moonlit-academy-478519-t8/book-app-docker-repo/book-app-image:$SHORT_SHA"]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "container", "clusters", "get-credentials",
        "$_GKE_CLUSTER",
        "--region=$_GKE_ZONE",
        "--project=moonlit-academy-478519-t8"
      ]
      
  - name: gcr.io/cloud-builders/kubectl
    args:
      [
        "apply", 
        "-f", 
        "k8s/deployment.yaml",
      ]
    env:
      - "CLOUDSDK_COMPUTE_REGION=$_GKE_ZONE"
      - "CLOUDSDK_CONTAINER_CLUSTER=$_GKE_CLUSTER"
      - "CLOUDSDK_PROJECT=moonlit-academy-478519-t8"

  - name: "gcr.io/cloud-builders/kubectl"  
    args: 
      [ 
        "set", "image", "deployment/book-app", 
        "book-app=us-central1-docker.pkg.dev/moonlit-academy-478519-t8/book-app-docker-repo/book-app-image:$SHORT_SHA", 
      ]
    env: 
      - "CLOUDSDK_COMPUTE_REGION=$_GKE_ZONE" 
      - "CLOUDSDK_CONTAINER_CLUSTER=$_GKE_CLUSTER"
    
  - name: "gcr.io/cloud-builders/kubectl"
    args:
      [
        "rollout", "status",
        "deployment/book-app",
        "--timeout=5m",
      ]
    env:
      - "CLOUDSDK_COMPUTE_REGION=$_GKE_ZONE"
      - "CLOUDSDK_CONTAINER_CLUSTER=$_GKE_CLUSTER"

images:
  - "us-central1-docker.pkg.dev/moonlit-academy-478519-t8/book-app-docker-repo/book-app-image"

substitutions:
  _GKE_CLUSTER: "books-cluster"
  _GKE_ZONE: "us-central1"
  _DB_NAME: "booksdb"
  _DB_USER: "book_user"
  _DB_PASSWORD: "root"

options:
  logging: CLOUD_LOGGING_ONLY