steps:
  - name: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.19.0
    id: cloudsql-and-flyway
    entrypoint: bash
    secretEnv: ["DB_PASSWORD"]
    args:
      - -c
      - |
        echo "======================================"
        echo "Starting Cloud SQL Proxy..."
        echo "Instance: ${_DB_INSTANCE}"
        echo "======================================"

        /cloud-sql-proxy \
          ${_DB_INSTANCE} \
          --port=3306 \
          --address=127.0.0.1 &

        sleep 5

        echo "Installing dependencies..."
        apk add --no-cache git bash curl unzip

        echo "======================================"
        echo "Cloning repository with caching..."
        echo "Repository: ${_REPO_URL}"
        echo "======================================"
        if [ ! -d "/workspace/Book_app/.git" ]; then
          git clone --depth 1 ${_REPO_URL} /workspace/Book_app
        else
          cd /workspace/Book_app
          git pull
        fi

        echo "======================================"
        echo "Installing Flyway..."
        echo "======================================"

        curl -L https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/10.12.0/flyway-commandline-10.12.0-linux-x64.tar.gz \
          -o flyway.tar.gz

        tar -xzf flyway.tar.gz
        mv flyway-10.12.0 flyway
        export PATH="$$PATH:/workspace/flyway"

        echo "======================================"
        echo "Running Flyway migration..."
        echo "DB_HOST: 127.0.0.1"
        echo "DB_NAME: ${_DB_NAME}"
        echo "======================================"

        flyway \
          -url=jdbc:mysql://127.0.0.1:3306/${_DB_NAME} \
          -user=${_DB_USER} \
          -password=$$DB_PASSWORD \
          -locations=filesystem:/workspace/Book_app/flyway/sql \
          migrate

        echo "======================================"
        echo "Flyway migration completed successfully!"
        echo "======================================"

  - name: gcr.io/cloud-builders/docker
    args:
      [
        "build",
        "-t", "us-central1-docker.pkg.dev/moonlit-academy-478519-t8/book-app-docker-repo/book-app-image:$SHORT_SHA",
        "."
      ]

  - name: gcr.io/cloud-builders/docker
    args: ["push", "us-central1-docker.pkg.dev/moonlit-academy-478519-t8/book-app-docker-repo/book-app-image:$SHORT_SHA"]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "container", "clusters", "get-credentials",
        "$_GKE_CLUSTER",
        "--region=$_GKE_ZONE",
        "--project=moonlit-academy-478519-t8"
      ]
      
  - name: gcr.io/cloud-builders/kubectl
    args:
      [
        "apply", 
        "-f", 
        "k8s/deployment.yaml",
      ]
    env:
      - "CLOUDSDK_COMPUTE_REGION=$_GKE_ZONE"
      - "CLOUDSDK_CONTAINER_CLUSTER=$_GKE_CLUSTER"
      - "CLOUDSDK_PROJECT=moonlit-academy-478519-t8"

  - name: "gcr.io/cloud-builders/kubectl"  
    args: 
      [ 
        "set", "image", "deployment/book-app", 
        "book-app=us-central1-docker.pkg.dev/moonlit-academy-478519-t8/book-app-docker-repo/book-app-image:$SHORT_SHA", 
      ]
    env: 
      - "CLOUDSDK_COMPUTE_REGION=$_GKE_ZONE" 
      - "CLOUDSDK_CONTAINER_CLUSTER=$_GKE_CLUSTER"
    
  - name: "gcr.io/cloud-builders/kubectl"
    args:
      [
        "rollout", "status",
        "deployment/book-app",
        "--timeout=5m",
      ]
    env:
      - "CLOUDSDK_COMPUTE_REGION=$_GKE_ZONE"
      - "CLOUDSDK_CONTAINER_CLUSTER=$_GKE_CLUSTER"

images:
  - "us-central1-docker.pkg.dev/moonlit-academy-478519-t8/book-app-docker-repo/book-app-image"

availableSecrets:
  secretManager:
    - versionName: "projects/$PROJECT_ID/secrets/db-book-password/versions/1"
      env: "DB_PASSWORD"

substitutions:
  _GKE_CLUSTER: "books-cluster"
  _GKE_ZONE: "us-central1"
  _HOME_USER: "vladkavalevich_test"
  _DB_ADDRESS: "127.0.0.1"
  _DB_PORT: "3306"
  _DB_INSTANCE: "moonlit-academy-478519-t8:us-central1:books-db"
  _DB_NAME: "booksdb"
  _DB_USER: "books_user"
  _REPO_URL: "https://github.com/VladislavKovalevich/Book_app.git"

options:
  logging: CLOUD_LOGGING_ONLY