steps:
  - name: liquibase/liquibase:4.23
    id: liquibase-migration
    entrypoint: /bin/sh
    args:
      - -c
      - |
        # Start Cloud SQL Proxy in background
        /cloud-sql-proxy --port=3306 --address=127.0.0.1 --private-ip moonlit-academy-478519-t8:us-central1:books-db &
        PROXY_PID=$!
        echo "Waiting for Cloud SQL Proxy to be ready..."
        # Wait until port 3306 is open
        for i in $(seq 1 30); do
          nc -z 127.0.0.1 3306 && break
          echo "Waiting for proxy... ($i/30)"
          sleep 2
        done

        # Run Liquibase migrations
        liquibase \
          --url=jdbc:mysql://127.0.0.1:3306/booksdb \
          --changeLogFile=liquibase/changelogs/db.changelog-master.yaml \
          --username=$$USERNAME \
          --password=$$PASSWORD \
          update

        # Kill the proxy after migration
        kill $$PROXY_PID
    secretEnv: ['USERNAME', 'PASSWORD']
  
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "build",
        "-t", "us-central1-docker.pkg.dev/moonlit-academy-478519-t8/book-app-docker-repo/book-app-image:$SHORT_SHA",
        "."
      ]

  - name: gcr.io/cloud-builders/docker
    args: ["push", "us-central1-docker.pkg.dev/moonlit-academy-478519-t8/book-app-docker-repo/book-app-image:$SHORT_SHA"]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "container", "clusters", "get-credentials",
        "$_GKE_CLUSTER",
        "--region=$_GKE_ZONE",
        "--project=moonlit-academy-478519-t8"
      ]
      
  - name: gcr.io/cloud-builders/kubectl
    args:
      [
        "apply", 
        "-f", 
        "k8s/deployment.yaml",
      ]
    env:
      - "CLOUDSDK_COMPUTE_REGION=$_GKE_ZONE"
      - "CLOUDSDK_CONTAINER_CLUSTER=$_GKE_CLUSTER"
      - "CLOUDSDK_PROJECT=moonlit-academy-478519-t8"

  - name: "gcr.io/cloud-builders/kubectl"  
    args: 
      [ 
        "set", "image", "deployment/book-app", 
        "book-app=us-central1-docker.pkg.dev/moonlit-academy-478519-t8/book-app-docker-repo/book-app-image:$SHORT_SHA", 
      ]
    env: 
      - "CLOUDSDK_COMPUTE_REGION=$_GKE_ZONE" 
      - "CLOUDSDK_CONTAINER_CLUSTER=$_GKE_CLUSTER"
    
  - name: "gcr.io/cloud-builders/kubectl"
    args:
      [
        "rollout", "status",
        "deployment/book-app",
        "--timeout=5m",
      ]
    env:
      - "CLOUDSDK_COMPUTE_REGION=$_GKE_ZONE"
      - "CLOUDSDK_CONTAINER_CLUSTER=$_GKE_CLUSTER"

availableSecrets:
  secretManager:
  - versionName: projects/moonlit-academy-478519-t8/secrets/db-password/versions/latest
    env: 'PASSWORD'
  - versionName: projects/moonlit-academy-478519-t8/secrets/db-user/versions/latest
    env: 'USERNAME'

images:
  - "us-central1-docker.pkg.dev/moonlit-academy-478519-t8/book-app-docker-repo/book-app-image"

substitutions:
  _GKE_CLUSTER: "books-cluster"
  _GKE_ZONE: "us-central1"

options:
  logging: CLOUD_LOGGING_ONLY