steps:
  - name: debian:bullseye-slim
    id: cloudsql-and-flyway
    secretEnv: ["DB_PASSWORD"]
    entrypoint: 'bash'
    args:
      - -c
      - |
        apt-get update && apt-get install -y curl tar default-jdk git
        
        curl -o /usr/local/bin/cloud-sql-proxy https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v2.11.0/cloud-sql-proxy.linux.amd64
        chmod +x /usr/local/bin/cloud-sql-proxy

        curl -L https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/10.12.0/flyway-commandline-10.12.0-linux-x64.tar.gz -o flyway.tar.gz
        tar -xvf flyway.tar.gz
        mv flyway-10.12.0 /opt/flyway
        ln -s /opt/flyway/flyway /usr/local/bin/flyway
        
        git clone https://github.com/VladislavKovalevich/Book_app.git

        cloud-sql-proxy moonlit-academy-478519-t8:us-central1:books-db --port=$_DB_PORT --address=$_DB_ADDRESS &
        sleep 5

        flyway -v
        
        if [ ! -d "/workspace/Book_app/.git" ]; then
          git clone --depth 1 ${_REPO_URL} /workspace/Book_app
        fi

        flyway \
          -url=jdbc:mysql://127.0.0.1:3306/${_DB_NAME} \
          -user=${_DB_USER} \
          -password=$$DB_PASSWORD \
          -locations=filesystem:/workspace/Book_app/flyway/sql \
          repair

        flyway \
          -url=jdbc:mysql://127.0.0.1:3306/${_DB_NAME} \
          -user=${_DB_USER} \
          -password=$$DB_PASSWORD \
          -locations=filesystem:/workspace/Book_app/flyway/sql \
          migrate

  - name: gcr.io/cloud-builders/docker
    args:
      [
        "build",
        "-t", "us-central1-docker.pkg.dev/moonlit-academy-478519-t8/book-app-docker-repo/book-app-image:$SHORT_SHA",
        "."
      ]

  - name: gcr.io/cloud-builders/docker
    args: ["push", "us-central1-docker.pkg.dev/moonlit-academy-478519-t8/book-app-docker-repo/book-app-image:$SHORT_SHA"]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "container", "clusters", "get-credentials",
        "$_GKE_CLUSTER",
        "--region=$_GKE_ZONE",
        "--project=moonlit-academy-478519-t8"
      ]
      
  - name: gcr.io/cloud-builders/kubectl
    args:
      [
        "apply", 
        "-f", 
        "k8s/deployment.yaml",
      ]
    env:
      - "CLOUDSDK_COMPUTE_REGION=$_GKE_ZONE"
      - "CLOUDSDK_CONTAINER_CLUSTER=$_GKE_CLUSTER"
      - "CLOUDSDK_PROJECT=moonlit-academy-478519-t8"

  - name: "gcr.io/cloud-builders/kubectl"  
    args: 
      [ 
        "set", "image", "deployment/book-app", 
        "book-app=us-central1-docker.pkg.dev/moonlit-academy-478519-t8/book-app-docker-repo/book-app-image:$SHORT_SHA", 
      ]
    env: 
      - "CLOUDSDK_COMPUTE_REGION=$_GKE_ZONE" 
      - "CLOUDSDK_CONTAINER_CLUSTER=$_GKE_CLUSTER"
    
  - name: "gcr.io/cloud-builders/kubectl"
    args:
      [
        "rollout", "status",
        "deployment/book-app",
        "--timeout=5m",
      ]
    env:
      - "CLOUDSDK_COMPUTE_REGION=$_GKE_ZONE"
      - "CLOUDSDK_CONTAINER_CLUSTER=$_GKE_CLUSTER"

images:
  - "us-central1-docker.pkg.dev/moonlit-academy-478519-t8/book-app-docker-repo/book-app-image"

availableSecrets:
  secretManager:
    - versionName: "projects/494155220288/secrets/DB_BOOK_PASSWORD/versions/latest"
      env: "DB_PASSWORD"

substitutions:
  _GKE_CLUSTER: "books-cluster"
  _GKE_ZONE: "us-central1"
  _HOME_USER: "vladkavalevich_test"
  _DB_ADDRESS: "127.0.0.1"
  _DB_PORT: "3306"
  _DB_INSTANCE: "moonlit-academy-478519-t8:us-central1:books-db"
  _DB_NAME: "booksdb"
  _DB_USER: "books_user"
  _REPO_URL: "https://github.com/VladislavKovalevich/Book_app.git"

options:
  logging: CLOUD_LOGGING_ONLY