steps:
  # Cloud SQL Proxy
  - name: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.11.3
    id: cloud-sql-proxy
    args:
      [
        "--port=3306",
        "--address=0.0.0.0",
        "--private-ip",
        "moonlit-academy-478519-t8:us-central1:books-db"
      ]
    waitFor: ["-"]

  # Flyway migration using secrets
  - name: flyway/flyway:9.23.1
    id: flyway-migration
    waitFor: ["cloud-sql-proxy"]
    entrypoint: flyway
    args:
      [
        "migrate",
        "-url=jdbc:mysql://127.0.0.1:3306/booksdb",
        "-locations=filesystem:flyway/sql"
      ]
    env:
      - "FLYWAY_USER=$DB_USER"
      - "FLYWAY_PASSWORD=$DB_PASS"
      - "CLOUDSDK_COMPUTE_REGION=$_GKE_ZONE"

  # Docker build
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "build",
        "-t", "us-central1-docker.pkg.dev/moonlit-academy-478519-t8/book-app-docker-repo/book-app-image:$SHORT_SHA",
        "."
      ]

  # Docker push
  - name: gcr.io/cloud-builders/docker
    args: ["push", "us-central1-docker.pkg.dev/moonlit-academy-478519-t8/book-app-docker-repo/book-app-image:$SHORT_SHA"]

  # GKE credentials
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "container", "clusters", "get-credentials",
        "$_GKE_CLUSTER",
        "--region=$_GKE_ZONE",
        "--project=moonlit-academy-478519-t8"
      ]
      
  # Apply Kubernetes deployment
  - name: gcr.io/cloud-builders/kubectl
    args:
      [
        "apply", 
        "-f", 
        "k8s/deployment.yaml",
      ]
    env:
      - "CLOUDSDK_COMPUTE_REGION=$_GKE_ZONE"
      - "CLOUDSDK_CONTAINER_CLUSTER=$_GKE_CLUSTER"
      - "CLOUDSDK_PROJECT=moonlit-academy-478519-t8"

  # Update deployment image
  - name: "gcr.io/cloud-builders/kubectl"  
    args: 
      [ 
        "set", "image", "deployment/book-app", 
        "book-app=us-central1-docker.pkg.dev/moonlit-academy-478519-t8/book-app-docker-repo/book-app-image:$SHORT_SHA", 
      ]
    env: 
      - "CLOUDSDK_COMPUTE_REGION=$_GKE_ZONE" 
      - "CLOUDSDK_CONTAINER_CLUSTER=$_GKE_CLUSTER"
    
  # Rollout status check
  - name: "gcr.io/cloud-builders/kubectl"
    args:
      [
        "rollout", "status",
        "deployment/book-app",
        "--timeout=5m",
      ]
    env:
      - "CLOUDSDK_COMPUTE_REGION=$_GKE_ZONE"
      - "CLOUDSDK_CONTAINER_CLUSTER=$_GKE_CLUSTER"

# Secrets correctly referenced
secrets:
- secretEnv:
    DB_USER: projects/moonlit-academy-478519-t8/secrets/db-user/versions/1
    DB_PASS: projects/moonlit-academy-478519-t8/secrets/db-password/versions/1

# Docker image output
images:
  - "us-central1-docker.pkg.dev/moonlit-academy-478519-t8/book-app-docker-repo/book-app-image"

# Substitutions
substitutions:
  _GKE_CLUSTER: "books-cluster"
  _GKE_ZONE: "us-central1"

# Logging options
options:
  logging: CLOUD_LOGGING_ONLY