steps:
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "build",
        "-t", "us-central1-docker.pkg.dev/moonlit-academy-478519-t8/book-app-docker-repo/book-app-image:$SHORT_SHA",
        "."
      ]

  - name: gcr.io/cloud-builders/docker
    args: ["push", "us-central1-docker.pkg.dev/moonlit-academy-478519-t8/book-app-docker-repo/book-app-image:$SHORT_SHA"]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "container", "clusters", "get-credentials",
        "$_GKE_CLUSTER",
        "--zone=$_GKE_ZONE",
        "--project=moonlit-academy-478519-t8"
      ]

  - name: "gcr.io/cloud-builders/kubectl"
    args:
      [
        "set", "image",
        "deployment/books-app",
        "app=us-central1-docker.pkg.dev/moonlit-academy-478519-t8/book-app-docker-repo/book-app-image:$SHORT_SHA",
        "-n", "books"
      ]
    env:
      - "CLOUDSDK_COMPUTE_REGION=$_GKE_ZONE"
      - "CLOUDSDK_CONTAINER_CLUSTER=$_GKE_CLUSTER"

  - name: "gcr.io/cloud-builders/kubectl"
    args:
      [
        "rollout", "status",
        "deployment/books-app",
        "-n", "books"
      ]
    env:
      - "CLOUDSDK_COMPUTE_REGION=$_GKE_ZONE"
      - "CLOUDSDK_CONTAINER_CLUSTER=$_GKE_CLUSTER"

images:
  - "us-central1-docker.pkg.dev/moonlit-academy-478519-t8/book-app-docker-repo/book-app-image"

substitutions:
  _GKE_CLUSTER: "books-cluster"
  _GKE_ZONE: "us-central1-a"

options:
  logging: CLOUD_LOGGING_ONLY