steps:
  - name: debian:bullseye-slim
    id: cloudsql-and-flyway
    secretEnv: ["DB_PASSWORD", "DB_USER"]
    entrypoint: 'bash'
    args:
      - -c
      - |
        set -e

        apt-get update && apt-get install -y curl tar default-jdk git netcat-openbsd
        
        curl -o /usr/local/bin/cloud-sql-proxy https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v2.11.0/cloud-sql-proxy.linux.amd64
        chmod +x /usr/local/bin/cloud-sql-proxy

        curl -L https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/10.12.0/flyway-commandline-10.12.0-linux-x64.tar.gz -o flyway.tar.gz
        tar -xvf flyway.tar.gz
        mv flyway-10.12.0 /opt/flyway
        ln -s /opt/flyway/flyway /usr/local/bin/flyway
                
        if [ ! -d "/workspace/Book_app/.git" ]; then
          git clone --depth 1 ${_REPO_URL} /workspace/Book_app
        fi

        cloud-sql-proxy $PROJECT_ID:${_REGION}:${_DB_INSTANCE_NAME} \
            --port=${_DB_PORT} --address=${_DB_ADDRESS} &
        
        echo "Waiting for Cloud SQL Proxy..."
        until nc -z ${_DB_ADDRESS} ${_DB_PORT}; do
          sleep 1
        done
        
        cat <<EOF > flyway.conf
        flyway.url=jdbc:mysql://${_DB_ADDRESS}:${_DB_PORT}/${_DB_NAME}
        flyway.user=$$DB_USER
        flyway.password=$$DB_PASSWORD
        flyway.locations=filesystem:/workspace/Book_app/flyway/sql
        EOF

        chmod 600 flyway.conf

        flyway -v
        flyway -configFiles=flyway.conf repair
        flyway -configFiles=flyway.conf migrate

        rm flyway.conf

  - name: gcr.io/cloud-builders/docker
    args:
      [
        "build",
        "-t", "${_REGION}-docker.pkg.dev/$PROJECT_ID/book-app-docker-repo/book-app-image:${SHORT_SHA}",
        "."
      ]

  - name: gcr.io/cloud-builders/docker
    args: ["push", "${_REGION}-docker.pkg.dev/$PROJECT_ID/book-app-docker-repo/book-app-image:${SHORT_SHA}"]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "container", "clusters", "get-credentials",
        "$_GKE_CLUSTER",
        "--region=$_GKE_REGION",
        "--project=$PROJECT_ID"
      ]
      
  - name: gcr.io/cloud-builders/kubectl
    args:
      [
        "apply", "-f", "k8s/",
      ]
    env:
      - "CLOUDSDK_COMPUTE_REGION=$_GKE_REGION"
      - "CLOUDSDK_CONTAINER_CLUSTER=$_GKE_CLUSTER"
      - "CLOUDSDK_PROJECT=$PROJECT_ID"

  - name: "gcr.io/cloud-builders/kubectl"  
    args: 
      [ 
        "set", "image", "deployment/book-app", 
        "book-app=${_REGION}-docker.pkg.dev/$PROJECT_ID/book-app-docker-repo/book-app-image:${SHORT_SHA}", 
      ]
    env: 
      - "CLOUDSDK_COMPUTE_REGION=$_GKE_REGION" 
      - "CLOUDSDK_CONTAINER_CLUSTER=$_GKE_CLUSTER"
    
  - name: "gcr.io/cloud-builders/kubectl"
    args:
      [
        "rollout", "status",
        "deployment/book-app",
        "--timeout=5m",
      ]
    env:
      - "CLOUDSDK_COMPUTE_REGION=$_GKE_REGION"
      - "CLOUDSDK_CONTAINER_CLUSTER=$_GKE_CLUSTER"

images:
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/book-app-docker-repo/book-app-image"

availableSecrets:
  secretManager:
    - versionName: "projects/414825273014/secrets/db-password/versions/latest"
      env: "DB_PASSWORD"
    - versionName: "projects/414825273014/secrets/db-user/versions/latest"
      env: "DB_USER"

substitutions:
  _REGION: "us-central1"
  _GKE_CLUSTER: "books-cluster"
  _GKE_REGION: "us-central1"
  _DB_ADDRESS: "127.0.0.1"
  _DB_PORT: "3306"
  _DB_INSTANCE_NAME: "books-db"
  _DB_NAME: "books-db"
  _REPO_URL: "https://github.com/VladislavKovalevich/Book_app.git"

options:
  logging: CLOUD_LOGGING_ONLY