steps:
  - name: 'gcr.io/cloudsql-docker/gce-proxy:2.11.0'
    id: 'cloud-sql-proxy'
    entrypoint: '/cloud_sql_proxy'
    args:
      [
        "moonlit-academy-478519-t8:us-central1:books-db",
        "--port=$_DB_PORT",
        "-address=$_DB_ADDRESS"
      ]
    waitFor: ['-']

  - name: 'flyway/flyway:10.12.0'
    id: 'flyway-migrate'
    secretEnv: ['_DB_USER', '_DB_PASSWORD']
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        apk add --no-cache git bash curl
        git clone https://github.com/VladislavKovalevich/Book_app.git /workspace/Book_app
        /flyway/flyway \
            -url=jdbc:mysql://127.0.0.1:5432/booksdb \
            -user=$DB_USER \
            -password=$DB_PASSWORD \
            -locations=filesystem:/workspace/Book_app/flyway/sql \
        migrate

  - name: gcr.io/cloud-builders/docker
    args:
      [
        "build",
        "-t", "us-central1-docker.pkg.dev/moonlit-academy-478519-t8/book-app-docker-repo/book-app-image:$SHORT_SHA",
        "."
      ]

  - name: gcr.io/cloud-builders/docker
    args: ["push", "us-central1-docker.pkg.dev/moonlit-academy-478519-t8/book-app-docker-repo/book-app-image:$SHORT_SHA"]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "container", "clusters", "get-credentials",
        "$_GKE_CLUSTER",
        "--region=$_GKE_ZONE",
        "--project=moonlit-academy-478519-t8"
      ]
      
  - name: gcr.io/cloud-builders/kubectl
    args:
      [
        "apply", 
        "-f", 
        "k8s/deployment.yaml",
      ]
    env:
      - "CLOUDSDK_COMPUTE_REGION=$_GKE_ZONE"
      - "CLOUDSDK_CONTAINER_CLUSTER=$_GKE_CLUSTER"
      - "CLOUDSDK_PROJECT=moonlit-academy-478519-t8"

  - name: "gcr.io/cloud-builders/kubectl"  
    args: 
      [ 
        "set", "image", "deployment/book-app", 
        "book-app=us-central1-docker.pkg.dev/moonlit-academy-478519-t8/book-app-docker-repo/book-app-image:$SHORT_SHA", 
      ]
    env: 
      - "CLOUDSDK_COMPUTE_REGION=$_GKE_ZONE" 
      - "CLOUDSDK_CONTAINER_CLUSTER=$_GKE_CLUSTER"
    
  - name: "gcr.io/cloud-builders/kubectl"
    args:
      [
        "rollout", "status",
        "deployment/book-app",
        "--timeout=5m",
      ]
    env:
      - "CLOUDSDK_COMPUTE_REGION=$_GKE_ZONE"
      - "CLOUDSDK_CONTAINER_CLUSTER=$_GKE_CLUSTER"

secrets:
- secretEnv:
    _DB_USER: projects/moonlit-academy-478519-t8/secrets/db-book-user/versions/1
    _DB_PASSWORD: projects/moonlit-academy-478519-t8/secrets/db-book-password/versions/1

images:
  - "us-central1-docker.pkg.dev/moonlit-academy-478519-t8/book-app-docker-repo/book-app-image"

substitutions:
  _GKE_CLUSTER: "books-cluster"
  _GKE_ZONE: "us-central1"
  _DB_NAME: "booksdb"
  _HOME_USER: "vladkavalevich_test"
  _DB_ADDRESS: "127.0.0.1"
  _DB_PORT: "3306"

options:
  logging: CLOUD_LOGGING_ONLY